version: '3.8'

services:
    react-app:
        image: lanepact-test
        build:
            context: .
            dockerfile: Dockerfile
            args:
                REACT_APP_ENV: ${REACT_APP_ENV}
                REACT_APP_BASEURL: ${REACT_APP_BASEURL}
        restart: always
        ports:
            - '3030:3030'
        environment:
            - REACT_APP_ENV=${REACT_APP_ENV}
            - REACT_APP_BASEURL=${REACT_APP_BASEURL}
        labels:
            - traefik.enable=true
            - traefik.http.routers.react-app.rule=Host(`react-app.lanepact.com`)
            - traefik.http.services.react-app.loadbalancer.server.port=80
            - traefik.http.routers.react-app.entrypoints=websecure
            - traefik.http.routers.react-app.tls=true
            - traefik.http.routers.react-app.tls.certresolver=myresolver
            - traefik.http.routers.react-app.middlewares=redirect-to-https@file
